In [ ]:
class Email:
    def __init__(self,name,age):
        self.name =name
        self.age=age

e1 =Email(1,2)
print(e1.__dict__)

#dict is special attribute, to see the object 

{'name': 1, 'age': 2}


In [4]:
class Emp:
    def __init__(self,name,age):
        self.name =name
        self.age=age
    def sum(self):
        sum1 = 10 + self.age
        return sum1
    
e1 = Emp('aan',12)

e1.sum()

22

In [ ]:
attributes, objects, methods, constructor

In [ ]:
# __init__ magic method automatically called, amd variable initialised , called constructor
# 1) parameterized 2) Non parametrrized 3) Default constructor

In [ ]:
# 2)     def __init__(self):
#         self.name =21
#         self.age=23

# 1)     def __init__(self,name,age):
#         self.name =name
#         self.age=age

# 3) class Employee:
#         pass

#without constructor object cannot be created

In [ ]:
# once u create a object, memory will be allocated in heap, 
# that memory reference will be assigned to self (memory reference for that object)

# ex : 273543434.age

In [ ]:
# every opbejct when created a copy of the init var will be created 

In [ ]:
# memory allocation
# memeory reference returned to the object
# memeory reference automotically passed inside constructor
# constructor creates/ init variables at that memeory reference

In [ ]:
class memebers = attributes and actions

In [2]:
import pickle

# Replace with the path to your .p file
file_path = '/home/athenaik/GRPO_test/RLKGF/Data/DXY/dataset_dxy/goal_dict_original_dxy.p'

with open(file_path, 'rb') as f:
    data = pickle.load(f)

# Now you can inspect what's inside
print(type(data))        # Check the type of the object
print(len(data))         # If it's a list/dict, see how many items
print(data.keys())          # If it's a list, print first 2 items
# or
print(data.keys())       # If it's a dictionary


<class 'dict'>
3
dict_keys(['all', 'test', 'train'])
dict_keys(['all', 'test', 'train'])


In [3]:
for key, value in data.items():
    print(f"\n🔑 Key: {key}")
    print("📦 Type:", type(value))
    if isinstance(value, list):
        print("🔍 First 2 items:", value[:2])
    elif isinstance(value, dict):
        print("🔍 Keys:", list(value.keys())[:5])
    else:
        print("🔍 Value:", value)



🔑 Key: all
📦 Type: <class 'list'>
🔍 First 2 items: [{'disease_tag': '过敏性鼻炎', 'request_slots': {'disease': 'UNK'}, 'implicit_inform_slots': {'打喷嚏': False, '过敏': True}, 'explicit_inform_slots': {'咳嗽': True, '流涕': True}}, {'disease_tag': '上呼吸道感染', 'request_slots': {'disease': 'UNK'}, 'implicit_inform_slots': {'肺部湿啰音': False, '咳嗽': True}, 'explicit_inform_slots': {'发烧': True, '喘气': True, '烦躁不安': True}}]

🔑 Key: test
📦 Type: <class 'list'>
🔍 First 2 items: [{'disease_tag': '小儿手足口病', 'request_slots': {'disease': 'UNK'}, 'implicit_inform_slots': {'厌食': False, '咳嗽': False, '呕吐': False, '精神萎靡': True, '疱疹': True}, 'explicit_inform_slots': {'发烧': True, '烦躁不安': True, '皮疹': True}}, {'disease_tag': '小儿腹泻', 'request_slots': {'disease': 'UNK'}, 'implicit_inform_slots': {'厌食': True}, 'explicit_inform_slots': {'发烧': True, '稀便': True, '烦躁不安': True}}]

🔑 Key: train
📦 Type: <class 'list'>
🔍 First 2 items: [{'disease_tag': '过敏性鼻炎', 'request_slots': {'disease': 'UNK'}, 'implicit_inform_slots': {'打喷嚏': False

In [4]:
print(f"Total 'all' items: {len(data['all'])}")
print(f"Total 'train' items: {len(data['train'])}")
print(f"Total 'test' items: {len(data['test'])}")

total = len(data['all']) + len(data['train']) + len(data['test'])
print(f"Total items combined: {total}")


Total 'all' items: 524
Total 'train' items: 421
Total 'test' items: 103
Total items combined: 1048


In [ ]:
🔑 Key: all
📦 Type: <class 'list'>
🔍 First 2 items: [{'disease_tag': 'allergic rhinitis', 'request_slots': {'disease': 'UNK'}, 'implicit_inform_slots': {'sneezing': False, 'allergic': True}, 'explicit_inform_slots': {'cough': True, 'runny nose': True}}, {'disease_tag': 'upper respiratory infection', 'request_slots': {'disease': 'UNK'}, 'implicit_inform_slots': {'clear rales': False, 'cough': True}, 'explicit_inform_slots': {'Fever': True, 'Gasp': True, 'Irritable': True}}]

🔑 Key: test
📦 Type: <class 'list'>
🔍 First 2 items: [{'disease_tag': 'Pediatric hand, foot and mouth disease', 'request_slots': {'disease': 'UNK'}, 'implicit_inform_slots': {'anorexia': False, 'cough': False, 'vomiting': False, 'apathy': True, 'herpes': True}, 'explicit_inform_slots': {'fever': True, 'restlessness': True, 'rash': True}}, {'disease_tag': 'Children's diarrhea', 'request_slots': {'disease': 'UNK'}, 'implicit_inform_slots': {'Anorexia': True}, 'explicit_inform_slots': {'Fever': True, 'Loose stools': True, 'Irritability': True}}]

🔑 Key: train
📦 Type: <class 'list'>
🔍 First 2 items: [{'disease_tag': 'Allergic rhinitis', 'request_slots': {'disease': 'UNK'}, 'implicit_inform_slots': {'sneeze': False, 'allergy': True}, 'explicit_inform_slots': {'cough': True, 'runny nose': True}}, {'disease_tag': 'Upper respiratory tract infection', 'request_slots': {'disease': 'UNK'}, 'implicit_inform_slots': {'Pulmonary crackles': False, 'Cough': True}, 'explicit_inform_slots': {'fever': True, 'panting': True, 'restless': True}}]

In [18]:
class Employee:
    def __init__(self,name,salary):
        self._name = name
        self.salary = salary

    def display(self):
        print(f"{self.name},{self.salary}")

e1 = Employee('aan',1111)

In [21]:
#print(e1._Employee__name)
print(e1._name)

aan


In [19]:
e1.__dict__

{'_name': 'aan', 'salary': 1111}

In [22]:
import json
from collections import defaultdict

# Load your new dataset
with open('Dataset.txt', 'r', encoding='utf-8') as f:
    # This assumes the content is a JSON list within a source tag, need to clean it first
    # A simplified loading approach:
    content = f.read()
    # Find the start and end of the JSON list
    start = content.find('[')
    end = content.rfind(']') + 1
    data = json.loads(content[start:end])

weighted_graph = defaultdict(lambda: defaultdict(int))

for record in data:
    problem = record['problem_tag']
    
    # Combine explicit and implicit slots
    all_slots = {**record['explicit_inform_slots'], **record['implicit_inform_slots']}
    
    for slot, value in all_slots.items():
        # You might only want to count 'true' values or count all occurrences
        if value: # Only count if the slot is true
             weighted_graph[problem][slot] += 1

# Now weighted_graph contains the frequency counts
# You can save this to your `prob_slot_num_dict_maintenance.txt`
with open('prob_slot_num_dict_maintenance.txt', 'w', encoding='utf-8') as f:
    f.write(str(dict(weighted_graph)))

print("New weighted graph file created!")

New weighted graph file created!


In [23]:
import json
from collections import defaultdict

# --- Start: Corrected part to load your specific dataset.txt format ---
with open('Dataset.txt', 'r', encoding='utf-8') as f:
    content = f.read()
    # Find the start and end of the JSON list
    start = content.find('[')
    end = content.rfind(']') + 1
    data = json.loads(content[start:end])
# --- End: Corrected part ---

# Use defaultdict to easily increment counts
weighted_graph = defaultdict(lambda: defaultdict(int))

# Iterate through the entire dataset to aggregate counts
for record in data:
    problem = record['problem_tag']
    all_slots = {**record.get('explicit_inform_slots', {}), **record.get('implicit_inform_slots', {})}
    
    for slot, value in all_slots.items():
        if value:  # Only count 'true' associations
            weighted_graph[problem][slot] += 1

# Convert defaultdicts to regular dicts for cleaner output
final_graph = {k: dict(v) for k, v in weighted_graph.items()}

# Save the new, aggregated weighted graph file
with open('prob_slot_num_dict_maintenance_weighted.txt', 'w', encoding='utf-8') as f:
    f.write(str(final_graph))

print("New AGGREGATED weighted graph file created!")

New AGGREGATED weighted graph file created!


In [24]:
import json
import csv
import re
import os

def generate_csv_for_neo4j():
    """
    Loads data from Dataset.txt and creates Neo4j-import-compatible CSV files
    for nodes (problems, slots) and their relationships.
    """
    input_filename = 'Dataset.txt'
    
    print("Starting CSV generation for Neo4j...")

    if not os.path.exists(input_filename):
        print(f"Error: '{input_filename}' not found.")
        return

    # --- Load and Clean the Dataset ---
    try:
        with open(input_filename, 'r', encoding='utf-8') as f:
            content = f.read()
            match = re.search(r'\[\s*\{.*\}\s*\]', content, re.DOTALL)
            if match:
                data = json.loads(match.group(0))
                print(f"Successfully loaded {len(data)} records.")
            else:
                print("Error: Could not find a valid JSON list in the file.")
                return
    except Exception as e:
        print(f"An error occurred while parsing the file: {e}")
        return

    # --- Collect all unique nodes and relationships ---
    all_problems = set()
    all_slots = set()
    relationships = set()

    for record in data:
        problem = record.get('problem_tag')
        if not problem:
            continue
        
        all_problems.add(problem)
        
        slots = {**record.get('explicit_inform_slots', {}), **record.get('implicit_inform_slots', {})}
        for slot, is_present in slots.items():
            if is_present:
                all_slots.add(slot)
                relationships.add((problem, slot))

    # --- Create mapping from name to a unique ID for Neo4j ---
    problem_to_id = {name: f"p_{i}" for i, name in enumerate(all_problems)}
    slot_to_id = {name: f"s_{i}" for i, name in enumerate(all_slots)}
    
    # --- Write Node Files ---
    # Problems
    with open('problems_header.csv', 'w', newline='', encoding='utf-8') as f:
        f.write('problemId:ID,name,:LABEL\n')
    with open('problems.csv', 'w', newline='', encoding='utf-8') as f:
        writer = csv.writer(f)
        for name, uid in problem_to_id.items():
            writer.writerow([uid, name, 'Problem'])
    print(f"Generated problems.csv with {len(all_problems)} nodes.")

    # Slots
    with open('slots_header.csv', 'w', newline='', encoding='utf-8') as f:
        f.write('slotId:ID,name,:LABEL\n')
    with open('slots.csv', 'w', newline='', encoding='utf-8') as f:
        writer = csv.writer(f)
        for name, uid in slot_to_id.items():
            writer.writerow([uid, name, 'Slot'])
    print(f"Generated slots.csv with {len(all_slots)} nodes.")

    # --- Write Relationship File ---
    with open('relationships_header.csv', 'w', newline='', encoding='utf-8') as f:
        f.write(':START_ID,:END_ID\n')
    with open('relationships.csv', 'w', newline='', encoding='utf-8') as f:
        writer = csv.writer(f)
        for problem_name, slot_name in relationships:
            start_id = problem_to_id[problem_name]
            end_id = slot_to_id[slot_name]
            writer.writerow([start_id, end_id])
    print(f"Generated relationships.csv with {len(relationships)} relationships.")
    
    print("\nCSV generation complete! Files are ready for Neo4j import.")

if __name__ == '__main__':
    generate_csv_for_neo4j()

Starting CSV generation for Neo4j...
Successfully loaded 349 records.
Generated problems.csv with 345 nodes.
Generated slots.csv with 1473 nodes.
Generated relationships.csv with 1683 relationships.

CSV generation complete! Files are ready for Neo4j import.


In [2]:
import json
import re

def create_entity_files(input_path="Dataset.txt"):
    """
    Parses the dataset file to extract unique problem tags and symptoms,
    then writes them to their respective output files.

    Args:
        input_path (str): The path to the dataset text file.
    """
    try:
        with open(input_path, 'r', encoding='utf-8') as f:
            content = f.read()
    except FileNotFoundError:
        print(f"Error: The file '{input_path}' was not found.")
        return

    # Correctly remove lines using the valid regex
    cleaned_content = re.sub(r'\\', '', content)

    try:
        # Load the cleaned content as a JSON object (a list of dictionaries)
        data = json.loads(cleaned_content)
    except json.JSONDecodeError as e:
        print(f"Error: Could not parse the file as JSON. {e}")
        return

    problem_tags = set()
    symptoms = set()

    # Iterate through each record in the dataset
    for record in data:
        if "problem_tag" in record:
            problem_tags.add(record["problem_tag"])
        
        if "explicit_inform_slots" in record and isinstance(record["explicit_inform_slots"], dict):
            for symptom in record["explicit_inform_slots"].keys():
                symptoms.add(symptom)

    # Write the unique problem tags to omega_problems.txt
    with open("omega_problems.txt", 'w', encoding='utf-8') as f:
        # Sorting ensures a consistent order
        for tag in sorted(list(problem_tags)):
            f.write(tag + '\n')
            
    print(f"✅ Successfully created 'omega_problems.txt' with {len(problem_tags)} unique problem tags.")

    # Write the unique symptoms to omega_symptoms.txt
    with open("omega_symptoms.txt", 'w', encoding='utf-8') as f:
        # Sorting ensures a consistent order
        for symptom in sorted(list(symptoms)):
            f.write(symptom + '\n')
            
    print(f"✅ Successfully created 'omega_symptoms.txt' with {len(symptoms)} unique symptoms.")

# Run the function, assuming 'Dataset.txt' is in the same directory
create_entity_files("Dataset.txt")

✅ Successfully created 'omega_problems.txt' with 345 unique problem tags.
✅ Successfully created 'omega_symptoms.txt' with 998 unique symptoms.


In [28]:
import json
import pickle
import random

def split_dataset(input_path="Dataset.txt", output_path="omega_goals.p", train_ratio=0.8):
    # Read the dataset file
    try:
        with open(input_path, 'r', encoding='utf-8') as f:
            data = json.load(f)  # assuming Dataset.txt is valid JSON
    except FileNotFoundError:
        print(f"Error: File '{input_path}' not found.")
        return
    except json.JSONDecodeError as e:
        print(f"Error: Failed to decode JSON. {e}")
        return

    # Shuffle the data for random splitting
    random.shuffle(data)

    # Calculate split index
    split_idx = int(len(data) * train_ratio)

    # Split the data
    train_data = data[:split_idx]
    test_data = data[split_idx:]

    # Create the final dictionary
    final_dict = {
        'train': train_data,
        'test': test_data
    }

    # Save to pickle file
    with open(output_path, 'wb') as f:
        pickle.dump(final_dict, f)

    print(f"✅ Successfully saved train/test split to '{output_path}'.")
    print(f"Train size: {len(train_data)}, Test size: {len(test_data)}")

# Run the function
split_dataset()


✅ Successfully saved train/test split to 'omega_goals.p'.
Train size: 279, Test size: 70


In [4]:
import os
import torch
import torch.optim as optim
import pickle
import random
import numpy as np
import ast

# Assuming GCN.py and KG.py are in the same directory or accessible in the python path
from utils.utils import *
from utils import dialog_config
from Qwen25_3b_Test.DisPre_RWR_And_GCN.GCN import GCNReward
from Data.DXY.KG import KGADJ
from utils import dialog_config # Assuming this contains constants like TRUE/FALSE

# --- Helper Functions (to make the script self-contained) ---

def load_pickle(file):
    """Loads a pickle file."""
    with open(file, 'rb') as f:
        return pickle.load(f)

def text_to_list(file):
    """Reads a text file into a list of lines."""
    with open(file, 'r', encoding='utf-8') as f:
        return [line.strip() for line in f.readlines()]

def set_seed(seed):
    """Sets random seeds for reproducibility."""
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed(seed)
        torch.cuda.manual_seed_all(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False

# --- Main Training Function ---

def train_gcn_reward_model():
    """
    Main function to load data, train the GCNReward model, and save the best version.
    """
    # --- 1. Configuration and Setup ---
    set_seed(42)
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"Using device: {device}")

    # Hyperparameters
    epochs = 50
    learning_rate = 0.001
    batch_size = 16
    embed_size = 128 # Can be tuned

    # Define file paths for your new Omega dataset
    # Assumes these files are in a subdirectory named 'omega_data'
    data_path = './' # Change if your data is in a different folder
    problems_file = os.path.join(data_path, 'omega_problems.txt')
    observations_file = os.path.join(data_path, 'omega_symptoms.txt')
    goal_file = os.path.join(data_path, 'omega_goals.p')
    problem_obs_dict_file = os.path.join(data_path, 'prob_slot_num_dict_maintenance_weighted.txt')
    save_path = './omega_gcn_reward.pth.tar'

    # --- 2. Load Data and Build Knowledge Graph ---
    problems = text_to_list(problems_file)
    observations = text_to_list(observations_file)
    goals = load_pickle(goal_file)

    num_problems = len(problems)
    num_observations = len(observations)
    num_total_nodes = num_problems + num_observations

    # Create the slot_set dictionary mapping entities to indices
    slot_set = {**{prob: i for i, prob in enumerate(problems)}, 
                **{obs: i + num_problems for i, obs in enumerate(observations)}}

    # The KGADJ class needs the problem-symptom dictionary to build the adjacency matrix.
    # We rename the original files it expects internally for it to work.
    # This is a workaround to avoid modifying KG.py
    # if not os.path.exists('diseases_dxy.txt'):
    #     os.rename(problems_file, 'diseases_dxy.txt')
    # if not os.path.exists('symptoms_dxy.txt'):
    #     os.rename(observations_file, 'symptoms_dxy.txt')
    # if not os.path.exists('dise_sym_num_dict_dxy.txt'):
    #     with open(os.path.join(data_path, 'dise_sym_num_dict_dxy.txt'), 'r', encoding='utf-8') as f:
    #         content = f.read()
    #         self.dis_sys_pre = ast.literal_eval(content)


    kg = KGADJ(device, num_problems, num_observations, data_path)
    kg.initialize_adj() # This creates the adjacency matrix
    
    # Restore original filenames
    # os.rename('diseases_dxy.txt', problems_file)
    # os.rename('symptoms_dxy.txt', observations_file)
    # os.remove('dise_sym_num_dict_dxy.txt')


    # Convert the adjacency matrix to edge_index format for PyTorch Geometric
    adj_matrix = kg.kg_matrix
    edge_index = adj_matrix.nonzero().t().contiguous().to(device)

    # --- 3. Initialize Model and Optimizer ---
    model = GCNReward(
        device=device,
        kg_node=num_total_nodes,
        dis_num=num_problems,
        kggraph=kg,
        slot_set=slot_set,
        embed_size=embed_size
    ).to(device)

    optimizer = optim.Adam(model.parameters(), lr=learning_rate)
    
    print(f"Model initialized with {num_problems} problems and {num_observations} observations.")
    
    # --- 4. Training and Validation Loop ---
    best_accuracy = 0.0
    
    train_data = goals['train']
    test_data = goals['test']

    for epoch in range(epochs):
        model.train()
        total_loss = 0
        total_correct = 0
        total_samples = 0
        
        # Shuffle training data each epoch
        random.shuffle(train_data)
        
        # --- Training Phase ---
        for i in range(0, len(train_data), batch_size):
            batch = train_data[i:i+batch_size]
            if not batch:
                continue

            labels = []
            masks = []

            for goal_item in batch:
                print("Example train_data item:", train_data[0])
                print("Type:", type(train_data[0]))

                goal = goal_item['problem_tag']
                
                # Create label: the index of the correct problem
                problem_tag = goal_item['problem_tag']
                if problem_tag in problems:
                    labels.append(problems.index(problem_tag))
                else:
                    continue # Skip if problem tag is not found
                
                # Create mask: a vector indicating present observations
                mask = torch.zeros(num_total_nodes)
                # confirmed_obs = [k for k, v in goal['current_slots']['inform_slots'].items() if v == dialog_config.TRUE]
                confirmed_obs = []

                # Combine explicit and implicit slots with TRUE values
                for slot_dict in [goal_item.get('explicit_inform_slots', {}), goal_item.get('implicit_inform_slots', {})]:
                    confirmed_obs.extend([k for k, v in slot_dict.items() if v == dialog_config.TRUE])

                for obs in confirmed_obs:
                    if obs in slot_set:
                        mask[slot_set[obs]] = 1.0
                masks.append(mask)

            if not labels:
                continue

            labels_tensor = torch.LongTensor(labels).to(device)
            masks_tensor = torch.stack(masks).to(device)

            optimizer.zero_grad()
            #print("disease_ shape:", disease_.shape)   # Should be [batch_size, num_classes] e.g. [16, 345]
            print("labels_tensor shape:", labels_tensor.shape)  # Should be [batch_size] e.g. [16]
            print("labels_tensor:", labels_tensor)

            # Use the forward_before method for direct classification training
            correct, loss = model.forward_before(labels_tensor, edge_index, masks_tensor)
            
            loss.backward()
            optimizer.step()

            total_loss += loss.item() * len(batch)
            total_correct += correct
            total_samples += len(batch)
            
        avg_train_loss = total_loss / total_samples
        train_accuracy = total_correct / total_samples

        # --- Validation Phase ---
        model.eval()
        total_val_correct = 0
        total_val_samples = 0
        with torch.no_grad():
            for i in range(0, len(test_data), batch_size):
                batch = test_data[i:i+batch_size]
                if not batch:
                    continue

                labels = []
                masks = []
                for goal_item in batch:
                    #goal = goal_item['problem_tag']
                    problem_tag = goal_item['problem_tag']
                    if problem_tag in problems:
                        labels.append(problems.index(problem_tag))
                    else:
                        continue
                    
                    mask = torch.zeros(num_total_nodes)
                    # confirmed_obs = [k for k, v in goal['current_slots']['inform_slots'].items() if v == dialog_config.TRUE]
                    confirmed_obs = []

                    # Combine explicit and implicit slots with TRUE values
                    for slot_dict in [goal_item.get('explicit_inform_slots', {}), goal_item.get('implicit_inform_slots', {})]:
                        confirmed_obs.extend([k for k, v in slot_dict.items() if v == dialog_config.TRUE])

                    for obs in confirmed_obs:
                        if obs in slot_set:
                            mask[slot_set[obs]] = 1.0
                    masks.append(mask)

                if not labels:
                    continue
                    
                labels_tensor = torch.LongTensor(labels).to(device)
                masks_tensor = torch.stack(masks).to(device)
                
                correct, _ = model.forward_before(labels_tensor, edge_index, masks_tensor)
                total_val_correct += correct
                total_val_samples += len(batch)
        
        val_accuracy = total_val_correct / total_val_samples
        
        print(f"Epoch {epoch+1}/{epochs} | Train Loss: {avg_train_loss:.4f} | Train Acc: {train_accuracy:.4f} | Val Acc: {val_accuracy:.4f}")

        # --- 5. Save the Best Model ---
        if val_accuracy > best_accuracy:
            best_accuracy = val_accuracy
            torch.save({
                'state_dict': model.state_dict(),
                'best_accuracy': best_accuracy,
                'epoch': epoch + 1
            }, save_path)
            print(f"  -> New best model saved to {save_path} with accuracy: {best_accuracy:.4f}")

if __name__ == "__main__":
    train_gcn_reward_model()


Using device: cuda
Model initialized with 345 problems and 998 observations.
Example train_data item: {'problem_tag': 'intermittent_tpms_connection_after_replacement', 'request_slots': {'problem': 'UNK'}, 'explicit_inform_slots': {'rotary_unit_was_replaced': True, 'tpms_errors_are_random': True, 'rj45_connector_clicked_in': False, 'mounting_bracket_is_secure': True}, 'implicit_inform_slots': {'loose_rj45_wire_connection': True, 'improper_connector_seating': True}}
Type: <class 'dict'>
Example train_data item: {'problem_tag': 'intermittent_tpms_connection_after_replacement', 'request_slots': {'problem': 'UNK'}, 'explicit_inform_slots': {'rotary_unit_was_replaced': True, 'tpms_errors_are_random': True, 'rj45_connector_clicked_in': False, 'mounting_bracket_is_secure': True}, 'implicit_inform_slots': {'loose_rj45_wire_connection': True, 'improper_connector_seating': True}}
Type: <class 'dict'>
Example train_data item: {'problem_tag': 'intermittent_tpms_connection_after_replacement', 'reque

RuntimeError: Expected target size [16, 345], got [16]

In [1]:
import pickle

# Load problems and symptoms
with open('omega_problems.txt') as f:
    problems = [line.strip() for line in f.readlines()]

with open('omega_symptoms.txt') as f:
    symptoms = [line.strip() for line in f.readlines()]

# # Load prob-slot dictionary (you might need to eval or parse it if it's a string representation)
# with open('prob_slot_num_dict_maintenance_weighted.txt') as f:
#     prob_slot_dict = eval(f.read())

# # Load omega_goals.p (assuming it is pickled)
# with open('omega_goals.p', 'rb') as f:
#     goals = pickle.load(f)
    
#     #goals = list(goals.values())

#     print(goals)



In [2]:
import os
import pickle
import torch
from torch.utils.data import DataLoader
from torch.optim import Adam
import torch.nn.functional as F
from utils.utils import *
from Data.DXY.KG import KGADJ
from utils import dialog_config
from torch_geometric.utils import dense_to_sparse


from Qwen25_3b_Test.DisPre_RWR_And_GCN.GCN import GCNReward

# Assuming KGADJ and GCNReward are defined as you gave

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

# Paths
data_path = './'  # adjust to your data folder
omega_goals_path = os.path.join(data_path, 'omega_goals.p')

# Load KG adjacency info
kg_adj = KGADJ(device=device,
               dis_num=len(problems),    # set your disease number based on omega_problems.txt length
               sym_num=len(symptoms),    # set your symptom number based on omega_symptoms.txt length
               data_path=data_path)

kg_adj.initialize_adj()


/home/athenaik/GRPO_test/.venv/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [4]:
print(kg_adj.kg_matrix)
print(kg_adj.kg_matrix.shape)

tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]], device='cuda:0')
torch.Size([1343, 1343])


In [14]:
# Load training data
with open(omega_goals_path, 'rb') as f:
    data = pickle.load(f)
print(data.keys())
print(len(data['train']))
print(len(data['test']))

dict_keys(['train', 'test'])
279
70


In [16]:
train_goals = data['train']
print(train_goals)

[{'problem_tag': 'blockloader_y_axis_spindle_damage', 'request_slots': {'problem': 'UNK'}, 'explicit_inform_slots': {'y_axis_spindle_looks_damaged': True, 'y_axis_spindle_is_dirty': True, 'y_axis_spindle_grease_film_absent': False}, 'implicit_inform_slots': {'y_axis_spindle_may_need_replacement': True, 'y_axis_spindle_requires_cleaning': True}}, {'problem_tag': 'conveyor_belt_worn_out', 'request_slots': {'problem': 'UNK'}, 'explicit_inform_slots': {'deep_grooves_on_belt': True, 'belt_weave_is_peeling': True, 'wire_slipping_in_drive': True, 'belt_tension_checked': False}, 'implicit_inform_slots': {'belt_replacement_required': True, 'drive_not_functional': True}}, {'problem_tag': 'tpms_jerky_movement', 'request_slots': {'problem': 'UNK'}, 'explicit_inform_slots': {'tpms_movement_is_not_smooth': True, 'belts_look_fine': True, 'threaded_spindle_is_dry': True, 'linear_rails_not_cleaned': True}, 'implicit_inform_slots': {'lubrication_maintenance_overdue': True, 'mechanical_resistance_is_caus

In [17]:
# Map disease to index for labels
disease_to_idx = {d: i for i, d in enumerate(kg_adj.disease_pre)}
print(disease_to_idx)

{'accelerated_wear_on_components': 0, 'acd_error_after_blade_maintenance': 1, 'acd_fault_after_holder_install': 2, 'air_leak_after_moving_centering_module': 3, 'air_leak_in_untwisting_module': 4, 'approval_button_logic_error': 5, 'automatic_guide_tensioning_issue': 6, 'axis_movement_blocked_after_setup': 7, 'bad_cut_quality_after_blade_replacement': 8, 'bad_part_container_not_emptied': 9, 'bad_part_unit_ejection_failure': 10, 'bearing_surface_lubrication_failure': 11, 'belt_adjustment_fasteners_stuck': 12, 'belt_drive_length_inaccuracy': 13, 'belt_drive_noise_after_replacement': 14, 'belt_drive_tension_asymmetry': 15, 'belt_drive_tension_mismatch': 16, 'belt_drive_tension_unstable': 17, 'belt_overhangs_crown_gear': 18, 'belt_overtensioned_after_adjustment': 19, 'belt_tension_incorrect_after_adjustment': 20, 'belt_tension_pin_ineffective': 21, 'belt_tension_reading_impossible': 22, 'blade_contamination_issue': 23, 'blade_holder_removal_stuck': 24, 'blade_holders_binding_after_install': 

In [19]:
# Prepare a function to create training samples
def create_sample(goal):
    # Label
    label = disease_to_idx.get(goal['problem_tag'], -1)
    if label == -1:
        return None  # unknown disease, skip

    # Prepare symptom mask (1 if symptom confirmed, else 0)
    symptom_mask = torch.zeros(kg_adj.sym_num)
    for symp, val in goal['explicit_inform_slots'].items():
        if symp in kg_adj.sys_pre and val is True:
            idx = kg_adj.sys_pre.index(symp)
            symptom_mask[idx] = 1
    

    # Build full mask for kg_node = diseases + symptoms
    mask = torch.zeros(kg_adj.dis_num + kg_adj.sym_num)
    mask[kg_adj.dis_num:] = symptom_mask  # symptoms part set
    print(mask)
    return torch.tensor(label), mask

# Filter and prepare dataset
dataset = []
for g in train_goals:
    sample = create_sample(g)
    if sample is not None:
        dataset.append(sample)


tensor([0., 0., 0.,  ..., 1., 1., 0.])
tensor([0., 0., 0.,  ..., 0., 0., 0.])
tensor([0., 0., 0.,  ..., 0., 0., 0.])
tensor([0., 0., 0.,  ..., 0., 0., 0.])
tensor([0., 0., 0.,  ..., 0., 0., 0.])
tensor([0., 0., 0.,  ..., 0., 0., 0.])
tensor([0., 0., 0.,  ..., 0., 0., 0.])
tensor([0., 0., 0.,  ..., 0., 0., 0.])
tensor([0., 0., 0.,  ..., 1., 0., 0.])
tensor([0., 0., 0.,  ..., 0., 0., 0.])
tensor([0., 0., 0.,  ..., 0., 0., 0.])
tensor([0., 0., 0.,  ..., 0., 0., 0.])
tensor([0., 0., 0.,  ..., 0., 0., 0.])
tensor([0., 0., 0.,  ..., 0., 0., 0.])
tensor([0., 0., 0.,  ..., 0., 0., 0.])
tensor([0., 0., 0.,  ..., 0., 0., 0.])
tensor([0., 0., 0.,  ..., 0., 0., 0.])
tensor([0., 0., 0.,  ..., 0., 0., 0.])
tensor([0., 0., 0.,  ..., 0., 0., 0.])
tensor([0., 0., 0.,  ..., 0., 0., 0.])
tensor([0., 0., 0.,  ..., 0., 0., 0.])
tensor([0., 0., 0.,  ..., 0., 0., 0.])
tensor([0., 0., 0.,  ..., 0., 0., 0.])
tensor([0., 0., 0.,  ..., 0., 0., 0.])
tensor([0., 0., 0.,  ..., 0., 0., 0.])
tensor([0., 0., 0.,  ...,

In [ ]:

# DataLoader for batching
batch_size = 16
dataloader = DataLoader(dataset, batch_size=batch_size, shuffle=True)

# Initialize model
model = GCNReward(device=device,
                  kg_node=kg_adj.dis_num + kg_adj.sym_num,
                  dis_num=kg_adj.dis_num,
                  kggraph=kg_adj,
                  slot_set={**{d: i for i, d in enumerate(kg_adj.disease_pre)},
                            **{s: i + kg_adj.dis_num for i, s in enumerate(kg_adj.sys_pre)}},
                  embed_size=100).to(device)

optimizer = Adam(model.parameters(), lr=0.001)

# Helper function: convert dense adjacency matrix batch to edge_index list and edge_weight list
def batch_dense_to_sparse(adj_batch):
    # adj_batch: [B, N, N]
    edge_indices = []
    edge_weights = []
    for i in range(adj_batch.size(0)):
        edge_index, edge_weight = dense_to_sparse(adj_batch[i])
        edge_indices.append(edge_index)
        edge_weights.append(edge_weight)
    return edge_indices, edge_weights

# Modify your model's forward method to accept edge_index and edge_weight
def forward_with_edge_index(self, label, edge_index, mask, edge_weight=None):
    # x shape: [batch_size, num_nodes] = node indices, embedding lookup done inside model
    batch_size = mask.size(0)
    x = torch.tensor([[i for i in range(self.kg_node)] for _ in range(batch_size)]).to(self.device)
    x_embed = self.sym_representation(x)

    x_out = []
    for b in range(batch_size):
        h = F.relu(self.gc1(x_embed[b], edge_index[b], edge_weight[b] if edge_weight is not None else None))
        h = self.gc2(h, edge_index[b], edge_weight[b] if edge_weight is not None else None)
        x_out.append(h)

    x = torch.stack(x_out, dim=0)  # [batch_size, num_nodes, embed_size]

    x = x[:, :self.dis_num]  # only diseases, shape: [batch_size, dis_num, embed_size]

    mask_disease = mask[:, :self.dis_num]  # shape: [batch_size, dis_num]

    x = x * mask_disease.unsqueeze(-1)  # broadcast mask to [batch_size, dis_num, embed_size]

    # Now sum over embedding dimension for final prediction scores
    x = x.sum(dim=2)  # shape: [batch_size, dis_num]

    prob = torch.softmax(x, dim=1)
    loss = torch.nn.CrossEntropyLoss()(x, label)

    correct = (torch.argmax(prob, dim=1) == label).sum().item()


    return correct, loss


# Attach the new forward method to your model class
import types
model.forward = types.MethodType(forward_with_edge_index, model)

# Training loop
epochs = 10
model.train()

for epoch in range(epochs):
    total_loss = 0
    total_correct = 0
    total_samples = 0

    for labels, masks in dataloader:
        labels = labels.to(device)
        masks = masks.to(device)

        model.kgraph.initialize_adj()
        kg_matrix = model.kgraph.kg_matrix.unsqueeze(0).repeat(labels.size(0), 1, 1)

        edge_indices, edge_weights = batch_dense_to_sparse(kg_matrix)

        optimizer.zero_grad()

        batch_correct = 0
        batch_loss = 0
        for i in range(labels.size(0)):
            label_i = labels[i].unsqueeze(0)
            mask_i = masks[i].unsqueeze(0)
            edge_index_i = edge_indices[i].to(device)
            edge_weight_i = edge_weights[i].to(device)

            correct, loss = model.forward(label_i, [edge_index_i], mask_i, edge_weight=[edge_weight_i])
            loss.backward()
            optimizer.step()

            batch_correct += correct
            batch_loss += loss.item()

        total_loss += batch_loss
        total_correct += batch_correct
        total_samples += labels.size(0)

    print(f"Epoch {epoch+1}/{epochs}, Loss: {total_loss/total_samples:.4f}, Accuracy: {total_correct/total_samples:.4f}")


Epoch 1/10, Loss: 5.8435, Accuracy: 0.0036
Epoch 2/10, Loss: 5.8435, Accuracy: 0.0036
Epoch 3/10, Loss: 5.8435, Accuracy: 0.0036
Epoch 4/10, Loss: 5.8435, Accuracy: 0.0036
Epoch 5/10, Loss: 5.8435, Accuracy: 0.0036
Epoch 6/10, Loss: 5.8435, Accuracy: 0.0036
Epoch 7/10, Loss: 5.8435, Accuracy: 0.0036
Epoch 8/10, Loss: 5.8435, Accuracy: 0.0036
Epoch 9/10, Loss: 5.8435, Accuracy: 0.0036
Epoch 10/10, Loss: 5.8435, Accuracy: 0.0036


In [20]:
!pip install python-docx


   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.2/5.2 MB 32.9 MB/s  0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [python-docx] [python-docx]


In [25]:
from docx import Document
from docx.shared import Pt

def set_font_and_size(run, size):
    """Sets the font and size for a run object."""
    run.font.name = 'Calibri'
    run.font.size = Pt(size)

def generate_resume():
    """
    Generates an ATS-friendly resume in .docx format from structured data.
    """
    # --- Resume Data ---
    # All information is sourced from your provided resume PDF.
    resume_data = {
        "name": "Atheeth Anoop Naik",  
        "contact": "+4917617289166 | naikatheeth@gmail.com | Karolinenstr 44, Fürth, Bavaria",  
        "summary": "AI/ML professional with experience applying advanced machine learning and generative AI techniques to solve real-world problems. Skilled in Python, PyTorch, SQL, and data engineering tools (Databricks, Snowflake, Power BI). Proven ability to design and deploy AI-driven solutions for practical, real-time challenges. Strong communicator, collaborator, and fast learner, actively seeking full-time opportunities in Germany to apply technical expertise to innovative challenges.", # [cite: 4, 5, 6, 7]
        
        "experience": [
            {
                "company": "Siemens Healthineers | Forchheim", 
                "role": "Working Student in Data Science & Analytics", 
                "date": "02/2024 - Present",
                "details": [
                    "Custom AI Chatbot Prototype: Developed a chatbot using a RAG pipeline with LLAMA 3 and ChromaDB embeddings.", # [cite: 11]
                    "Implemented custom chunking to improve retrieval accuracy and built a GUI for seamless interaction.", # [cite: 12]
                    "Analyzed hospital imaging performance data in Snowflake, developed custom benchmarking metrics to detect inefficiencies, and prepared Excel/Power BI reports highlighting potential upgrade opportunities.", # [cite: 13]
                    "Processed hospital protocol and license usage data in Databricks using SQL and Python text-processing.", # [cite: 14]
                    "Identified upselling opportunities and created dashboards to support targeted marketing campaigns.", # [cite: 15]
                    "Time-Series Forecasting: Enhanced forecasting workflows (ARIMA, SARIMA, Exponential Smoothing) in Databricks for population and disease trends across 100+ countries.", # [cite: 16]
                    "Modularized workflows for reusability and automated country-specific PowerPoint reports.", # [cite: 17]
                    "AT Segmentation Dashboard: Extracted and processed data using Python and Pandas to segment customers for tailored sales strategies, improving marketing efficiency." # [cite: 18]
                ]
            },
            {
                "company": "Continental | Bangalore, Karnataka", # [cite: 19]
                "role": "Engineer", # [cite: 20]
                "date": "02/2021 - 09/2023",
                "details": [
                    "Developed modular Python scripts for automation testing of electronic control units, enabling plug-and-play reuse across multiple projects, improving testing efficiency and saving time and resources.", # [cite: 21]
                    "Supported CI/CD workflows for embedded software development, including Gerrit code reviews and automated testing pipelines, with some exposure to Jenkins automation.", # [cite: 22]
                    "Implemented and tested secure boot and secure flash functionality using AES-128, SHA256, and ECDSA cryptography in bootloader and end-of-line applications, ensuring robust data integrity and cybersecurity compliance.", # [cite: 23]
                    "Contributed to multiple OEM projects (Ferrari CRCM, Magna Fisker BCM, etc), quickly adapting to diverse project requirements and learning new tools and technologies as needed." # [cite: 24]
                ]
            },
            {
                "company": "KTES | Hubballi, Karnataka", # [cite: 25]
                "role": "Computer Vision Intern", # [cite: 26]
                "date": "09/2018 - 02/2019",
                "details": [
                    "Implemented OpenCV-based solutions for PCB defect detection, improving inspection accuracy and workflow efficiency." # [cite: 27]
                ]
            }
        ],

        "skills": {
            "Programming & Scripting": "Python, SQL, C++, Embedded C, Linux", # [cite: 29]
            "Machine Learning & AI": "Machine Learning, Deep Learning, Generative AI (LLMs, RAG pipelines), Computer Vision, Time-Series Forecasting, AI Algorithms", # [cite: 30]
            "Python Libraries & Frameworks": "PyTorch, NumPy, Pandas, Matplotlib, OpenCV, Scikit-learn", # [cite: 31]
            "Data Engineering & Cloud Tools": "Databricks, Snowflake, Docker, GitHub, MLOps, Power BI, AWS (basic), Azure (basic), Data Visualization & Analytics", # [cite: 32]
            "Development & Collaboration Tools": "Agile (Scrum, SAFe), Jira, Confluence, Requirement Analysis, Debugging & Testing, CI/CD, APIs (basic)", # [cite: 33]
            "Languages": "English (Fluent), Hindi, Tulu, Kannada, German (Beginner)" # [cite: 34]
        },

        "projects": [
            {
                "name": "Master's Thesis (Ongoing) - Fine-tuning LLMs using RL (GRPO) for Knowledge Graphs", # [cite: 36]
                "description": "Training domain-specific LLMs to enhance question answering and decision support for manufacturing data, by converting implicit human knowledge into structured knowledge graphs for retrieval and analysis." # [cite: 36]
            },
            {
                "name": "Deep Learning for Wound Segmentation (FAU, MaD Lab)", # [cite: 37]
                "description": "Developed and evaluated customized segmentation models leveraging U-Net, LinkNet, PSPNet, and FPN backbones in PyTorch for medical image segmentation, improving accuracy through comparative loss function analysis." # [cite: 37]
            },
            {
                "name": "Player Tracking with Adidas AG (FAU Project)", # [cite: 38]
                "description": "Built Deep Learning models for video-based player tracking; extracted insights such as ball speed, movement patterns, and heatmaps from the video." # [cite: 38, 39]
            },
            {
                "name": "Driver Drowsiness Detection (Bachelor's Project)", # [cite: 40]
                "description": "Trained RNNs model on EEG datasets to predict sleep stages and issue real-time driver alerts." 
            }
        ],
        
        "education": [
            {
                "institution": "FAU Erlangen-Nürnberg | Erlangen, Bavaria", # [cite: 42]
                "degree": "MSc in Artificial Intelligence with Minor in Business", # [cite: 43]
                "date": "Oct 2023 - Dec 2025 (Expected)", # [cite: 43]
                "details": "GPA 1.6 (90 ECTS)" # [cite: 43]
            },
            {
                "institution": "KLE Technological University | Hubballi, Karnataka", # [cite: 44]
                "degree": "Bachelor's in Electronics and Communication Engineering", # [cite: 45]
                "date": "August 2016 - December 2020", # [cite: 45]
                "details": "CGPA - 8.64/10.00" # [cite: 45]
            },
            {
                "institution": "Kle Technological University | Hubli, Karnataka", # [cite: 46]
                "degree": "Minor program in Entrepreneurship", # [cite: 47]
                "date": "Jun 2018 - Jan 2020", # [cite: 47]
                "details": "CGPA - 8.40/10.00" # [cite: 47]
            }
        ]
    }
    
    # --- Document Generation ---
    doc = Document()

    # Set document margins (optional)
    sections = doc.sections
    for section in sections:
        section.top_margin = Pt(72)
        section.bottom_margin = Pt(72)
        section.left_margin = Pt(72)
        section.right_margin = Pt(72)
        
    # Name and Contact
    p_name = doc.add_paragraph()
    run_name = p_name.add_run(resume_data['name'])
    run_name.bold = True
    set_font_and_size(run_name, 16)
    
    p_contact = doc.add_paragraph(resume_data['contact'])
    set_font_and_size(p_contact.runs[0], 11)
    
    # Summary
    doc.add_heading('Summary', level=1)
    p_summary = doc.add_paragraph(resume_data['summary'])
    set_font_and_size(p_summary.runs[0], 11)
    
    # Experience
    doc.add_heading('Experience', level=1)
    for job in resume_data['experience']:
        p_company = doc.add_paragraph()
        run_company = p_company.add_run(job['company'])
        run_company.bold = True
        
        p_role = doc.add_paragraph()
        run_role = p_role.add_run(job['role'] + ' | ' + job['date'])
        run_role.italic = True
        
        for detail in job['details']:
            doc.add_paragraph(detail, style='List Bullet')
        
        doc.add_paragraph() # Add a space after the job entry

    # Skills
    doc.add_heading('Skills', level=1)
    for category, skills_list in resume_data['skills'].items():
        p_skill = doc.add_paragraph()
        run_category = p_skill.add_run(category + ': ')
        run_category.bold = True
        p_skill.add_run(skills_list)
        
    # Projects
    doc.add_heading('Projects', level=1)
    for project in resume_data['projects']:
        p_project_name = doc.add_paragraph()
        run_project_name = p_project_name.add_run(project['name'])
        run_project_name.bold = True
        doc.add_paragraph(project['description'], style='List Bullet')
        
    # Education
    doc.add_heading('Education', level=1)
    for edu in resume_data['education']:
        p_institution = doc.add_paragraph()
        run_institution = p_institution.add_run(edu['institution'])
        run_institution.bold = True
        
        doc.add_paragraph(f"{edu['degree']} | {edu['date']}")
        doc.add_paragraph(edu['details'])
        doc.add_paragraph() # Add a space

    # Save the document
    file_name = 'Atheeth_Naik_Resume.docx'
    doc.save(file_name)
    print(f"✅ Successfully generated ATS-friendly resume: {file_name}")

if __name__ == '__main__':
    generate_resume()

✅ Successfully generated ATS-friendly resume: Atheeth_Naik_Resume.docx


TEST

In [17]:
import sys
import os
import ast # Assuming you need these from your original code
# Helper functions from your original code (placeholders)
def text_to_list(path):
    with open(path, 'r') as f:
        return [line.strip() for line in f.readlines()]

def load_pickle(path):
    import pickle
    with open(path, 'rb') as f:
        return pickle.load(f)

def text_to_dict(path):
    with open(path, 'r') as f:
        # This is just a guess at the function's logic
        return {line.strip(): i for i, line in enumerate(f.readlines())}


# --- Start of the corrected logic ---

# Get the current working directory instead of the script directory
base_path = os.getcwd() 
print("Current working dir:", base_path)

# If your code is in a subdirectory (e.g., 'scripts') of your project root,
project_root = os.path.abspath(os.path.join(base_path, '..'))
print("project_root",project_root)

# This replaces `sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))`
sys.path.append(project_root)
print("sys.path after append:", sys.path)

grand_path = base_path # Assuming grand_path is the project root

DXY_path = os.path.join(grand_path, 'Data', 'DXY', 'dataset_dxy')
print("DXY_path",DXY_path)

DXY_Disease = text_to_list(os.path.join(DXY_path, 'omega_problems.txt')) # problems
print("DXY_Disease",DXY_Disease)

DXY_Symptom = text_to_list(os.path.join(DXY_path, 'omega_symptoms.txt'))
print("DXY_Symptom",DXY_Symptom)

DXY_goal = load_pickle(os.path.join(DXY_path, 'omega_goals.p'))
print("DXY_goal",DXY_goal)

dis_sym_num_to_graph_path = os.path.join(DXY_path, 'prob_slot_num_dict_maintenance_weighted.txt')
print("dis_sym_num_to_graph_path",dis_sym_num_to_graph_path)

with open(dis_sym_num_to_graph_path, 'r', encoding='utf-8') as f:
    content = f.readlines()
    dis_sym_num_to_graph = ast.literal_eval(content[0])

#gcn_path = os.path.join(grand_path, 'useful_models', 'DXY_GCN', 'gcn_0.6675.pth.tar')
slot_set = text_to_dict('{}/omega_slot.txt'.format(DXY_path))
print("slot_set",slot_set)

print("\nSuccessfully defined paths.")

Current working dir: /home/athenaik/GRPO_test/RLKGF
project_root /home/athenaik/GRPO_test
sys.path after append: ['/opt/miniconda3/lib/python311.zip', '/opt/miniconda3/lib/python3.11', '/opt/miniconda3/lib/python3.11/lib-dynload', '', '/home/athenaik/GRPO_test/.venv/lib/python3.11/site-packages', '/tmp/tmp0dco19gr', '/home/athenaik/GRPO_test', '/home/athenaik/GRPO_test', '/home/athenaik/GRPO_test', '/home/athenaik/GRPO_test', '/home/athenaik/GRPO_test', '/home/athenaik/GRPO_test', '/home/athenaik/GRPO_test']
DXY_path /home/athenaik/GRPO_test/RLKGF/Data/DXY/dataset_dxy
DXY_Disease ['accelerated_wear_on_components', 'acd_error_after_blade_maintenance', 'acd_fault_after_holder_install', 'air_leak_after_moving_centering_module', 'air_leak_in_untwisting_module', 'approval_button_logic_error', 'automatic_guide_tensioning_issue', 'axis_movement_blocked_after_setup', 'bad_cut_quality_after_blade_replacement', 'bad_part_container_not_emptied', 'bad_part_unit_ejection_failure', 'bearing_surface_

In [ ]:
from utils.utils import *
from Data.DXY.KG import KGADJ
import torch

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

kgraph = KGADJ(device, len(DXY_Disease), len(DXY_Symptom), DXY_path)

#kgraph = KGADJ(device, dis_num, sym_num, data_path)
# kgraph.initialize_adj()
# adj_matrix = kgraph.kg_matrix  # tensor of shape [kg_node, kg_node]

kgraph.initialize_adj()
adj_matrix = kgraph.kg_matrix  # tensor of shape [kg_node, kg_node]


In [ ]:
model = GCNReward(
    device=device,
    kg_node=len(DXY_Disease) + len(DXY_Symptom),
    dis_num=len(DXY_Disease),
    kggraph=kgraph,
    slot_set=slot_set,  # mapping from slot name to index
    embed_size=100,
    temperature=0.5
)

In [41]:
import pickle

with open('omega_goals.p', 'rb') as f:
    data = pickle.load(f)

# train_data = data['train']
kg_node = len(DXY_Disease) + len(DXY_Symptom)

goal_ = GetAllSym(data)   # converts to format with 'current_slots'
train_data = goal_['train']

for sample in train_data:
    label_disease = sample['problem_tag']
    label = torch.tensor([disease2id[label_disease]]).to(device)

    state_input = model.state_representation(sample)  # returns (1, kg_node)

    # Create edge_index from current KG
    model.kgraph.initialize_adj()
    edge_index = model.construct_kg_index(model.kgraph.kg_matrix.view(1, kg_node, kg_node))

    output, loss = model.forward(label, edge_index, state_input)


KeyboardInterrupt: 

In [29]:
def GetAllSym(goal_set):
    new_goal_test = {'train': [], 'test': []}
    for g in goal_set['train']:
        g_ = {'current_slots': {'inform_slots': {}}, 'problem_tag': g['problem_tag']}
        for ex in g['explicit_inform_slots']:
            g_['current_slots']['inform_slots'][ex] = dialog_config.TRUE if g['explicit_inform_slots'][ex] else dialog_config.FALSE
        for im in g['implicit_inform_slots']:
            g_['current_slots']['inform_slots'][im] = dialog_config.TRUE if g['implicit_inform_slots'][im] else dialog_config.FALSE
        new_goal_test['train'].append(g_)

    for g in goal_set['test']:
        g_ = {'current_slots': {'inform_slots': {}}, 'problem_tag': g['problem_tag']}
        for ex in g['explicit_inform_slots']:
            g_['current_slots']['inform_slots'][ex] = dialog_config.TRUE if g['explicit_inform_slots'][ex] else dialog_config.FALSE
        for im in g['implicit_inform_slots']:
            g_['current_slots']['inform_slots'][im] = dialog_config.TRUE if g['implicit_inform_slots'][im] else dialog_config.FALSE
        new_goal_test['test'].append(g_)

    return new_goal_test


In [42]:
optimizer = torch.optim.Adam(model.parameters(), lr=1e-3)
from utils import dialog_config

import pickle

with open('omega_goals.p', 'rb') as f:
    data = pickle.load(f)

goal_ = GetAllSym(data)   # converts to format with 'current_slots'
train_data = goal_['train']


disease2id = {disease: slot_set[disease] for disease in DXY_Disease}

print(train_data[0])


for epoch in range(5):
    total_loss = 0
    total_correct = 0

    for sample in train_data:
        model.train()

        label = torch.tensor([disease2id[sample['problem_tag']]]).to(device)
        state_input = model.state_representation(sample)

        model.kgraph.initialize_adj()
        edge_index = model.construct_kg_index(model.kgraph.kg_matrix.view(1, kg_node, kg_node))

        optimizer.zero_grad()
        correct, loss = model.forward(label, edge_index, state_input)

        loss.backward()
        optimizer.step()

        total_loss += loss.item()
        total_correct += correct

    print(f"Epoch {epoch+1}: Loss = {total_loss:.4f}, Accuracy = {total_correct}/{len(train_data)}")


{'current_slots': {'inform_slots': {'y_axis_spindle_looks_damaged': 1, 'y_axis_spindle_is_dirty': 1, 'y_axis_spindle_grease_film_absent': -1, 'y_axis_spindle_may_need_replacement': 1, 'y_axis_spindle_requires_cleaning': 1}}, 'problem_tag': 'blockloader_y_axis_spindle_damage'}


KeyboardInterrupt: 

In [ ]:
import sys
import os
import ast # Assuming you need these from your original code
# Helper functions from your original code (placeholders)
def text_to_list(path):
    with open(path, 'r') as f:
        return [line.strip() for line in f.readlines()]

def load_pickle(path):
    import pickle
    with open(path, 'rb') as f:
        return pickle.load(f)

def text_to_dict(path):
    with open(path, 'r') as f:
        # This is just a guess at the function's logic
        return {line.strip(): i for i, line in enumerate(f.readlines())}


from Qwen25_3b_Test.DisPre_RWR_And_GCN.GCN import GCNReward

# --- Start of the corrected logic ---

# Get the current working directory instead of the script directory
base_path = os.getcwd() 
print("Current working dir:", base_path)

# If your code is in a subdirectory (e.g., 'scripts') of your project root,
project_root = os.path.abspath(os.path.join(base_path, '..'))
print("project_root",project_root)

# This replaces `sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))`
sys.path.append(project_root)
print("sys.path after append:", sys.path)

grand_path = base_path # Assuming grand_path is the project root

DXY_path = os.path.join(grand_path, 'Data', 'DXY', 'dataset_dxy')
print("DXY_path",DXY_path)

DXY_Disease = text_to_list(os.path.join(DXY_path, 'omega_problems.txt')) # problems
print("DXY_Disease",DXY_Disease)

DXY_Symptom = text_to_list(os.path.join(DXY_path, 'omega_symptoms.txt'))
print("DXY_Symptom",DXY_Symptom)

DXY_goal = load_pickle(os.path.join(DXY_path, 'omega_goals.p'))
print("DXY_goal",DXY_goal)

dis_sym_num_to_graph_path = os.path.join(DXY_path, 'prob_slot_num_dict_maintenance_weighted.txt')
print("dis_sym_num_to_graph_path",dis_sym_num_to_graph_path)

with open(dis_sym_num_to_graph_path, 'r', encoding='utf-8') as f:
    content = f.readlines()
    dis_sym_num_to_graph = ast.literal_eval(content[0])

#gcn_path = os.path.join(grand_path, 'useful_models', 'DXY_GCN', 'gcn_0.6675.pth.tar')
slot_set = text_to_dict('{}/omega_slot.txt'.format(DXY_path))
print("slot_set",slot_set)

print("\nSuccessfully defined paths.")

from utils.utils import *
from Data.DXY.KG import KGADJ
import torch

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

kgraph = KGADJ(device, len(DXY_Disease), len(DXY_Symptom), DXY_path)

#kgraph = KGADJ(device, dis_num, sym_num, data_path)
# kgraph.initialize_adj()
# adj_matrix = kgraph.kg_matrix  # tensor of shape [kg_node, kg_node]

kgraph.initialize_adj()
adj_matrix = kgraph.kg_matrix  # tensor of shape [kg_node, kg_node]


model = GCNReward(
    device=device,
    kg_node=len(DXY_Disease) + len(DXY_Symptom),
    dis_num=len(DXY_Disease),
    kggraph=kgraph,
    slot_set=slot_set,  # mapping from slot name to index
    embed_size=100,
    temperature=0.5
)

def GetAllSym(goal_set):
    new_goal_test = {'train': [], 'test': []}
    for g in goal_set['train']:
        g_ = {'current_slots': {'inform_slots': {}}, 'problem_tag': g['problem_tag']}
        for ex in g['explicit_inform_slots']:
            g_['current_slots']['inform_slots'][ex] = dialog_config.TRUE if g['explicit_inform_slots'][ex] else dialog_config.FALSE
        for im in g['implicit_inform_slots']:
            g_['current_slots']['inform_slots'][im] = dialog_config.TRUE if g['implicit_inform_slots'][im] else dialog_config.FALSE
        new_goal_test['train'].append(g_)

    for g in goal_set['test']:
        g_ = {'current_slots': {'inform_slots': {}}, 'problem_tag': g['problem_tag']}
        for ex in g['explicit_inform_slots']:
            g_['current_slots']['inform_slots'][ex] = dialog_config.TRUE if g['explicit_inform_slots'][ex] else dialog_config.FALSE
        for im in g['implicit_inform_slots']:
            g_['current_slots']['inform_slots'][im] = dialog_config.TRUE if g['implicit_inform_slots'][im] else dialog_config.FALSE
        new_goal_test['test'].append(g_)

    return new_goal_test


optimizer = torch.optim.Adam(model.parameters(), lr=1e-3)
from utils import dialog_config

import pickle

with open('omega_goals.p', 'rb') as f:
    data = pickle.load(f)

goal_ = GetAllSym(data)   # converts to format with 'current_slots'
train_data = goal_['train']


disease2id = {disease: slot_set[disease] for disease in DXY_Disease}

print(train_data[0])

# train_data = data['train']
kg_node = len(DXY_Disease) + len(DXY_Symptom)

for epoch in range(5):
    total_loss = 0
    total_correct = 0

    for sample in train_data:
        model.train()

        label = torch.tensor([disease2id[sample['problem_tag']]]).to(device)
        state_input = model.state_representation(sample)

        model.kgraph.initialize_adj()
        edge_index = model.construct_kg_index(model.kgraph.kg_matrix.view(1, kg_node, kg_node))

        optimizer.zero_grad()
        correct, loss = model.forward(label, edge_index, state_input)

        loss.backward()
        optimizer.step()

        total_loss += loss.item()
        total_correct += correct

    print(f"Epoch {epoch+1}: Loss = {total_loss:.4f}, Accuracy = {total_correct}/{len(train_data)}")


In [43]:
import time
start = time.time()
_ = model.state_representation(train_data[0])
print(f"Single state_representation call took {time.time()-start:.4f} seconds")


Single state_representation call took 0.0134 seconds


In [1]:
import sys
import os
import ast
import torch
import pickle
import time

from Qwen25_3b_Test.DisPre_RWR_And_GCN.GCN import GCNReward
from utils.utils import *
from Data.DXY.KG import KGADJ
from utils import dialog_config

start_time = time.time()
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"[Setup] Using device: {device}")

# Helper functions
def text_to_list(path):
    with open(path, 'r') as f:
        return [line.strip() for line in f.readlines()]

def load_pickle(path):
    with open(path, 'rb') as f:
        return pickle.load(f)

def text_to_dict(path):
    with open(path, 'r') as f:
        return {line.strip(): i for i, line in enumerate(f.readlines())}

# --- Setup paths ---
base_path = os.getcwd()
project_root = os.path.abspath(os.path.join(base_path, '..'))
sys.path.append(project_root)
grand_path = base_path
DXY_path = os.path.join(grand_path, 'Data', 'DXY', 'dataset_dxy')

print(f"[Setup] Base path: {base_path}")
print(f"[Setup] Project root appended to sys.path: {project_root}")

# Load lists and dicts
DXY_Disease = text_to_list(os.path.join(DXY_path, 'omega_problems.txt'))
DXY_Symptom = text_to_list(os.path.join(DXY_path, 'omega_symptoms.txt'))
print(f"[Setup] Loaded Diseases ({len(DXY_Disease)}), Symptoms ({len(DXY_Symptom)})")

DXY_goal = load_pickle(os.path.join(DXY_path, 'omega_goals.p'))

with open(os.path.join(DXY_path, 'prob_slot_num_dict_maintenance_weighted.txt'), 'r', encoding='utf-8') as f:
    content = f.readlines()
    dis_sym_num_to_graph = ast.literal_eval(content[0])

slot_set = text_to_dict(os.path.join(DXY_path, 'omega_slot.txt'))
print(f"[Setup] Loaded slot_set with {len(slot_set)} items")

# Initialize KG graph
kgraph = KGADJ(device, len(DXY_Disease), len(DXY_Symptom), DXY_path)
kgraph.initialize_adj()
print(f"[Setup] Knowledge graph adjacency matrix initialized")

# Initialize model
model = GCNReward(
    device=device,
    kg_node=len(DXY_Disease) + len(DXY_Symptom),
    dis_num=len(DXY_Disease),
    kggraph=kgraph,
    slot_set=slot_set,
    embed_size=1024,
    temperature=0.5
).to(device)

print(f"[Setup] Model initialized with embed_size=1024")

def GetAllSym(goal_set):
    new_goal_test = {'train': [], 'test': []}
    for g in goal_set['train']:
        g_ = {'current_slots': {'inform_slots': {}}, 'problem_tag': g['problem_tag']}
        for ex in g['explicit_inform_slots']:
            g_['current_slots']['inform_slots'][ex] = dialog_config.TRUE if g['explicit_inform_slots'][ex] else dialog_config.FALSE
        for im in g['implicit_inform_slots']:
            g_['current_slots']['inform_slots'][im] = dialog_config.TRUE if g['implicit_inform_slots'][im] else dialog_config.FALSE
        new_goal_test['train'].append(g_)

    for g in goal_set['test']:
        g_ = {'current_slots': {'inform_slots': {}}, 'problem_tag': g['problem_tag']}
        for ex in g['explicit_inform_slots']:
            g_['current_slots']['inform_slots'][ex] = dialog_config.TRUE if g['explicit_inform_slots'][ex] else dialog_config.FALSE
        for im in g['implicit_inform_slots']:
            g_['current_slots']['inform_slots'][im] = dialog_config.TRUE if g['implicit_inform_slots'][im] else dialog_config.FALSE
        new_goal_test['test'].append(g_)

    return new_goal_test

optimizer = torch.optim.Adam(model.parameters(), lr=1e-3)

goal_ = GetAllSym(DXY_goal)
train_data = goal_['train']

disease2id = {disease: slot_set[disease] for disease in DXY_Disease}

kg_node = len(DXY_Disease) + len(DXY_Symptom)

print(f"[Setup] Finished data preparation and model setup in {time.time() - start_time:.2f} seconds")


/home/athenaik/GRPO_test/.venv/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


[Setup] Using device: cuda
[Setup] Base path: /home/athenaik/GRPO_test/RLKGF
[Setup] Project root appended to sys.path: /home/athenaik/GRPO_test
[Setup] Loaded Diseases (345), Symptoms (998)
[Setup] Loaded slot_set with 1342 items
[Setup] Knowledge graph adjacency matrix initialized
[Setup] Model initialized with embed_size=1024
[Setup] Finished data preparation and model setup in 3.83 seconds


In [2]:
import time
print("[Precompute] Starting precomputation of state representations...")
start_precompute = time.time()

all_state_inputs = []
all_labels = []

for idx, sample in enumerate(train_data):
    if idx % 100 == 0 and idx > 0:
        print(f"[Precompute] Processed {idx}/{len(train_data)} samples")
    state_tensor = model.state_representation(sample)  # This should be CPU tensor
    all_state_inputs.append(state_tensor)
    all_labels.append(disease2id[sample['problem_tag']])

all_state_inputs = torch.stack(all_state_inputs).to(device)  # Move to GPU once
all_labels = torch.tensor(all_labels, dtype=torch.long).to(device)

print(f"[Precompute] Completed in {time.time() - start_precompute:.2f} seconds")
print(f"[Precompute] State inputs shape: {all_state_inputs.shape}")
print(f"[Precompute] Labels shape: {all_labels.shape}")


[Precompute] Starting precomputation of state representations...
[Precompute] Processed 100/279 samples
[Precompute] Processed 200/279 samples
[Precompute] Completed in 1.04 seconds
[Precompute] State inputs shape: torch.Size([279, 1, 1343])
[Precompute] Labels shape: torch.Size([279])


In [8]:
import os
import torch

# Set synchronous CUDA execution for better error messages
os.environ['CUDA_LAUNCH_BLOCKING'] = '1'

# Clear any previous CUDA errors
torch.cuda.empty_cache()
torch.cuda.synchronize()

print("[Setup] CUDA_LAUNCH_BLOCKING=1 enabled for better error reporting")
print("[Setup] CUDA cache cleared")

# Reinitialize the model to clear any corrupted state
model = GCNReward(
    device=device,
    kg_node=len(DXY_Disease) + len(DXY_Symptom),
    dis_num=len(DXY_Disease),
    kggraph=kgraph,
    slot_set=slot_set,
    embed_size=1024,
    temperature=0.5
).to(device)

optimizer = torch.optim.Adam(model.parameters(), lr=1e-3)

print("[Setup] Model reinitialized")

# Verify labels are still correct after reinitialization
print(f"[Verify] Label range: min={all_labels.min().item()}, max={all_labels.max().item()}")
print(f"[Verify] Expected range: [0, {len(DXY_Disease)-1}]")

# Now run the training loop again

[Setup] CUDA_LAUNCH_BLOCKING=1 enabled for better error reporting
[Setup] CUDA cache cleared
[Setup] Model reinitialized
[Verify] Label range: min=0, max=1133
[Verify] Expected range: [0, 344]


In [6]:
import time

#print("[Training] Starting training...")
start_training = time.time()

batch_size = 1
num_samples = all_labels.size(0)

#print("Before model.kgraph.initialize_adj()")
model.kgraph.initialize_adj()
#print("After model.kgraph.initialize_adj()")

start = time.time()
#print("Before edge_index = model.construct_kg_index")
edge_index = model.construct_kg_index(model.kgraph.kg_matrix.view(1, kg_node, kg_node)).to(device)
#print(f"Constructing and moving edge_index took {time.time() - start:.4f} seconds")

for epoch in range(5):
    print(f"[Training] Epoch {epoch+1} started")
    total_loss = 0.0
    total_correct = 0
    model.train()
    
    #print("Starting batch loop")
    epoch_start = time.time()

    for i in range(0, num_samples, batch_size):
        batch_inputs = all_state_inputs[i:i + batch_size].squeeze(1)
        batch_labels = all_labels[i:i + batch_size]

        print(f"  [Batch {i//batch_size}] Batch inputs shape: {batch_inputs.shape}, Batch labels shape: {batch_labels.shape}")

        batch_start = time.time()
        optimizer.zero_grad()

        print(f"  [Batch {i//batch_size}] Starting forward pass...")
        correct, loss = model.forward(batch_labels, edge_index, batch_inputs)
        print(f"  [Batch {i//batch_size}] Forward pass done in {time.time() - batch_start:.4f} seconds")

        print(f"  [Batch {i//batch_size}] Loss computed: {loss.item():.4f}")

        backward_start = time.time()
        loss.backward()
        optimizer.step()
        print(f"  [Batch {i//batch_size}] Backward and optimizer step done in {time.time() - backward_start:.4f} seconds")

        total_loss += loss.item()
        total_correct += correct

        if i % (batch_size * 10) == 0:
            print(f"  [Batch {i//batch_size}] Cumulative Loss={total_loss:.4f}, Correct={total_correct}")

    print("Finished batch loop")
    print(f"[Training] Epoch {epoch+1} completed in {time.time() - epoch_start:.2f} seconds")
    print(f"[Training] Epoch {epoch+1}: Total Loss={total_loss:.4f}, Accuracy={total_correct}/{num_samples}")

print(f"[Training] Total training time: {time.time() - start_training:.2f} seconds")


[Training] Starting training...
Before model.kgraph.initialize_adj()
After model.kgraph.initialize_adj()
Before edge_index = model.construct_kg_index
Constructing and moving edge_index took 0.0004 seconds
[Training] Epoch 1 started
Starting batch loop
  [Batch 0] Batch inputs shape: torch.Size([1, 1343]), Batch labels shape: torch.Size([1])
  [Batch 0] Starting forward pass...
  [Batch 0] Forward pass done in 5.0552 seconds
  [Batch 0] Loss computed: 5.8232
  [Batch 0] Backward and optimizer step done in 0.2783 seconds
  [Batch 0] Cumulative Loss=5.8232, Correct=1
  [Batch 1] Batch inputs shape: torch.Size([1, 1343]), Batch labels shape: torch.Size([1])
  [Batch 1] Starting forward pass...
  [Batch 1] Forward pass done in 5.3364 seconds
  [Batch 1] Loss computed: 5.7687
  [Batch 1] Backward and optimizer step done in 0.4013 seconds
  [Batch 2] Batch inputs shape: torch.Size([1, 1343]), Batch labels shape: torch.Size([1])
  [Batch 2] Starting forward pass...
  [Batch 2] Forward pass don

KeyboardInterrupt: 

In [7]:
# Create a proper disease-to-index mapping
# This ensures disease labels are in range [0, len(DXY_Disease)-1]
disease2id = {disease: idx for idx, disease in enumerate(DXY_Disease)}

print(f"[Setup] Created disease2id mapping with {len(disease2id)} diseases")
print(f"[Setup] Disease indices range: [0, {len(disease2id)-1}]")
print(f"[Setup] Sample mappings: {list(disease2id.items())[:5]}")

# Verify the mapping
assert len(disease2id) == len(DXY_Disease), "disease2id size mismatch!"
assert max(disease2id.values()) == len(DXY_Disease) - 1, "Max disease index incorrect!"
assert min(disease2id.values()) == 0, "Min disease index incorrect!"

print("[Setup] disease2id mapping verified successfully!")

[Setup] Created disease2id mapping with 345 diseases
[Setup] Disease indices range: [0, 344]
[Setup] Sample mappings: [('accelerated_wear_on_components', 0), ('acd_error_after_blade_maintenance', 1), ('acd_fault_after_holder_install', 2), ('air_leak_after_moving_centering_module', 3), ('air_leak_in_untwisting_module', 4)]
[Setup] disease2id mapping verified successfully!


In [ ]:
#WORKING:

In [1]:
import sys
import os
import ast
import torch
import pickle
import time

from Qwen25_3b_Test.DisPre_RWR_And_GCN.GCN import GCNReward
from utils.utils import *
from Data.DXY.KG import KGADJ
from utils import dialog_config

start_time = time.time()
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"[Setup] Using device: {device}")

# Helper functions
def text_to_list(path):
    with open(path, 'r') as f:
        return [line.strip() for line in f.readlines()]

def load_pickle(path):
    with open(path, 'rb') as f:
        return pickle.load(f)

def text_to_dict(path):
    with open(path, 'r') as f:
        return {line.strip(): i for i, line in enumerate(f.readlines())}

# --- Setup paths ---
base_path = os.getcwd()
project_root = os.path.abspath(os.path.join(base_path, '..'))
sys.path.append(project_root)
grand_path = base_path
DXY_path = os.path.join(grand_path, 'Data', 'DXY', 'dataset_dxy')

print(f"[Setup] Base path: {base_path}")
print(f"[Setup] Project root appended to sys.path: {project_root}")

# Load lists and dicts
DXY_Disease = text_to_list(os.path.join(DXY_path, 'omega_problems.txt'))
DXY_Symptom = text_to_list(os.path.join(DXY_path, 'omega_symptoms.txt'))
print(f"[Setup] Loaded Diseases ({len(DXY_Disease)}), Symptoms ({len(DXY_Symptom)})")

DXY_goal = load_pickle(os.path.join(DXY_path, 'omega_goals.p'))

with open(os.path.join(DXY_path, 'prob_slot_num_dict_maintenance_weighted.txt'), 'r', encoding='utf-8') as f:
    content = f.readlines()
    dis_sym_num_to_graph = ast.literal_eval(content[0])

slot_set = text_to_dict(os.path.join(DXY_path, 'omega_slot.txt'))
print(f"[Setup] Loaded slot_set with {len(slot_set)} items")

# Initialize KG graph
kgraph = KGADJ(device, len(DXY_Disease), len(DXY_Symptom), DXY_path)
kgraph.initialize_adj()
print(f"[Setup] Knowledge graph adjacency matrix initialized")

# # Initialize model
# model = GCNReward(
#     device=device,
#     kg_node=len(DXY_Disease) + len(DXY_Symptom),
#     dis_num=len(DXY_Disease),
#     kggraph=kgraph,
#     slot_set=slot_set,
#     embed_size=1024,
#     temperature=0.5
# ).to(device)

import os
import torch

# Set synchronous CUDA execution for better error messages
os.environ['CUDA_LAUNCH_BLOCKING'] = '1'

# Clear any previous CUDA errors
torch.cuda.empty_cache()
torch.cuda.synchronize()

print("[Setup] CUDA_LAUNCH_BLOCKING=1 enabled for better error reporting")
print("[Setup] CUDA cache cleared")

# Reinitialize the model to clear any corrupted state
model = GCNReward(
    device=device,
    kg_node=len(DXY_Disease) + len(DXY_Symptom),
    dis_num=len(DXY_Disease),
    kggraph=kgraph,
    slot_set=slot_set,
    embed_size=1024,
    temperature=0.5
).to(device)

optimizer = torch.optim.Adam(model.parameters(), lr=1e-3)

print("[Setup] Model reinitialized")


def GetAllSym(goal_set):
    new_goal_test = {'train': [], 'test': []}
    for g in goal_set['train']:
        g_ = {'current_slots': {'inform_slots': {}}, 'problem_tag': g['problem_tag']}
        for ex in g['explicit_inform_slots']:
            g_['current_slots']['inform_slots'][ex] = dialog_config.TRUE if g['explicit_inform_slots'][ex] else dialog_config.FALSE
        for im in g['implicit_inform_slots']:
            g_['current_slots']['inform_slots'][im] = dialog_config.TRUE if g['implicit_inform_slots'][im] else dialog_config.FALSE
        new_goal_test['train'].append(g_)

    for g in goal_set['test']:
        g_ = {'current_slots': {'inform_slots': {}}, 'problem_tag': g['problem_tag']}
        for ex in g['explicit_inform_slots']:
            g_['current_slots']['inform_slots'][ex] = dialog_config.TRUE if g['explicit_inform_slots'][ex] else dialog_config.FALSE
        for im in g['implicit_inform_slots']:
            g_['current_slots']['inform_slots'][im] = dialog_config.TRUE if g['implicit_inform_slots'][im] else dialog_config.FALSE
        new_goal_test['test'].append(g_)

    return new_goal_test

optimizer = torch.optim.Adam(model.parameters(), lr=1e-3)

goal_ = GetAllSym(DXY_goal)
train_data = goal_['train']

disease2id = {disease: slot_set[disease] for disease in DXY_Disease}

kg_node = len(DXY_Disease) + len(DXY_Symptom)

print(f"[Setup] Finished data preparation and model setup in {time.time() - start_time:.2f} seconds")

import time
print("[Precompute] Starting precomputation of state representations...")
start_precompute = time.time()

all_state_inputs = []
all_labels = []

for idx, sample in enumerate(train_data):
    if idx % 100 == 0 and idx > 0:
        print(f"[Precompute] Processed {idx}/{len(train_data)} samples")
    state_tensor = model.state_representation(sample)  # This should be CPU tensor
    all_state_inputs.append(state_tensor)
    all_labels.append(disease2id[sample['problem_tag']])

all_state_inputs = torch.stack(all_state_inputs).to(device)  # Move to GPU once
all_labels = torch.tensor(all_labels, dtype=torch.long).to(device)

print(f"[Precompute] Completed in {time.time() - start_precompute:.2f} seconds")
print(f"[Precompute] State inputs shape: {all_state_inputs.shape}")
print(f"[Precompute] Labels shape: {all_labels.shape}")


# Verify labels are still correct after reinitialization
print(f"[Verify] Label range: min={all_labels.min().item()}, max={all_labels.max().item()}")
print(f"[Verify] Expected range: [0, {len(DXY_Disease)-1}]")

# Now run the training loop again

print(f"[Setup] Model initialized with embed_size=1024")

import time

#print("[Training] Starting training...")
start_training = time.time()

batch_size = 1
num_samples = all_labels.size(0)

#print("Before model.kgraph.initialize_adj()")
model.kgraph.initialize_adj()
#print("After model.kgraph.initialize_adj()")

start = time.time()
#print("Before edge_index = model.construct_kg_index")
edge_index = model.construct_kg_index(model.kgraph.kg_matrix.view(1, kg_node, kg_node)).to(device)
#print(f"Constructing and moving edge_index took {time.time() - start:.4f} seconds")

for epoch in range(5):
    print(f"[Training] Epoch {epoch+1} started")
    total_loss = 0.0
    total_correct = 0
    model.train()
    
    #print("Starting batch loop")
    epoch_start = time.time()

    for i in range(0, num_samples, batch_size):
        batch_inputs = all_state_inputs[i:i + batch_size].squeeze(1)
        batch_labels = all_labels[i:i + batch_size]

        print(f"  [Batch {i//batch_size}] Batch inputs shape: {batch_inputs.shape}, Batch labels shape: {batch_labels.shape}")

        batch_start = time.time()
        optimizer.zero_grad()

        print(f"  [Batch {i//batch_size}] Starting forward pass...")
        correct, loss = model.forward(batch_labels, edge_index, batch_inputs)
        print(f"  [Batch {i//batch_size}] Forward pass done in {time.time() - batch_start:.4f} seconds")

        print(f"  [Batch {i//batch_size}] Loss computed: {loss.item():.4f}")

        backward_start = time.time()
        loss.backward()
        optimizer.step()
        print(f"  [Batch {i//batch_size}] Backward and optimizer step done in {time.time() - backward_start:.4f} seconds")

        total_loss += loss.item()
        total_correct += correct

        if i % (batch_size * 10) == 0:
            print(f"  [Batch {i//batch_size}] Cumulative Loss={total_loss:.4f}, Correct={total_correct}")

    print("Finished batch loop")
    print(f"[Training] Epoch {epoch+1} completed in {time.time() - epoch_start:.2f} seconds")
    print(f"[Training] Epoch {epoch+1}: Total Loss={total_loss:.4f}, Accuracy={total_correct}/{num_samples}")

print(f"[Training] Total training time: {time.time() - start_training:.2f} seconds")



/home/athenaik/GRPO_test/.venv/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


[Setup] Using device: cuda
[Setup] Base path: /home/athenaik/GRPO_test/RLKGF
[Setup] Project root appended to sys.path: /home/athenaik/GRPO_test
[Setup] Loaded Diseases (345), Symptoms (998)
[Setup] Loaded slot_set with 1342 items
[Setup] Knowledge graph adjacency matrix initialized
[Setup] CUDA_LAUNCH_BLOCKING=1 enabled for better error reporting
[Setup] CUDA cache cleared
[Setup] Model reinitialized
[Setup] Finished data preparation and model setup in 4.10 seconds
[Precompute] Starting precomputation of state representations...
[Precompute] Processed 100/279 samples
[Precompute] Processed 200/279 samples
[Precompute] Completed in 0.88 seconds
[Precompute] State inputs shape: torch.Size([279, 1, 1343])
[Precompute] Labels shape: torch.Size([279])
[Verify] Label range: min=0, max=1133
[Verify] Expected range: [0, 344]
[Setup] Model initialized with embed_size=1024
[Training] Epoch 1 started
  [Batch 0] Batch inputs shape: torch.Size([1, 1343]), Batch labels shape: torch.Size([1])
  [Ba

/pytorch/aten/src/ATen/native/cuda/Loss.cu:242: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [0,0,0] Assertion `t >= 0 && t < n_classes` failed.


RuntimeError: CUDA error: device-side assert triggered
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.


In [2]:
# Add this diagnostic code before your training loop
import torch

print("=" * 60)
print("DIAGNOSTIC CHECKS")
print("=" * 60)

# Check 1: Verify label range
print(f"\n1. Label Range Check:")
print(f"   Min label: {all_labels.min().item()}")
print(f"   Max label: {all_labels.max().item()}")
print(f"   Expected range: [0, {len(DXY_Disease)-1}]")
print(f"   Number of unique labels: {torch.unique(all_labels).numel()}")

# Check 2: Verify disease2id mapping
print(f"\n2. disease2id Mapping Check:")
print(f"   Number of diseases: {len(DXY_Disease)}")
print(f"   Number of mappings: {len(disease2id)}")
print(f"   Max ID in mapping: {max(disease2id.values())}")
print(f"   Min ID in mapping: {min(disease2id.values())}")

# Check 3: Sample some training data
print(f"\n3. Sample Training Data:")
for i in range(min(3, len(train_data))):
    sample = train_data[i]
    disease = sample['problem_tag']
    label_id = disease2id.get(disease, -1)
    print(f"   Sample {i}: disease='{disease}', label_id={label_id}")

# Check 4: Verify state representation shapes
print(f"\n4. State Representation Shape:")
print(f"   all_state_inputs.shape: {all_state_inputs.shape}")
print(f"   Expected: [num_samples, 1, kg_node] = [{len(train_data)}, 1, {kg_node}]")

# Check 5: Edge index check
print(f"\n5. Edge Index Check:")
print(f"   edge_index.shape: {edge_index.shape}")
print(f"   edge_index min: {edge_index.min().item()}")
print(f"   edge_index max: {edge_index.max().item()}")
print(f"   Expected max: {kg_node - 1}")

# Check 6: Model classifier output shape
print(f"\n6. Model Classifier Check:")
print(f"   Classifier output size: {model.classifier[0].out_features}")
print(f"   Should equal dis_num: {len(DXY_Disease)}")

# Check 7: Check for any NaN or Inf in inputs
print(f"\n7. NaN/Inf Check:")
print(f"   all_state_inputs has NaN: {torch.isnan(all_state_inputs).any().item()}")
print(f"   all_state_inputs has Inf: {torch.isinf(all_state_inputs).any().item()}")

# Check 8: Disease mask check (run one sample through)
print(f"\n8. Test Forward Pass (single sample):")
try:
    model.eval()
    with torch.no_grad():
        test_input = all_state_inputs[0:1].squeeze(1)
        test_label = all_labels[0:1]
        print(f"   Test input shape: {test_input.shape}")
        print(f"   Test label: {test_label.item()}")
        
        correct, loss = model.forward(test_label, edge_index, test_input)
        print(f"   Forward pass successful!")
        print(f"   Loss: {loss.item():.4f}")
except Exception as e:
    print(f"   ERROR during test forward pass: {e}")

print("=" * 60)
print("END DIAGNOSTIC CHECKS")
print("=" * 60)

DIAGNOSTIC CHECKS

1. Label Range Check:


RuntimeError: CUDA error: device-side assert triggered
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.


In [3]:
print(f"Batch labels: {batch_labels}")
assert (batch_labels >= 0).all() and (batch_labels < len(DXY_Disease)), "Labels out of range!"


RuntimeError: CUDA error: device-side assert triggered
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
